//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace dt1.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class db61a6afb29dc84f4597e3a2b500ebed20Entities : DbContext
    {
        public db61a6afb29dc84f4597e3a2b500ebed20Entities()
            : base("name=db61a6afb29dc84f4597e3a2b500ebed20Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<PriceData> PriceDatas { get; set; }
        public virtual DbSet<PriceChanx> PriceChanges { get; set; }
        public virtual DbSet<Log> Logs { get; set; }
        public virtual DbSet<Order> Orders { get; set; }
    }
}
