//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace dt1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        public int Id { get; set; }
        public string Coin { get; set; }
        public Nullable<System.DateTime> Timestamp { get; set; }
        public string Direction { get; set; }
        public Nullable<decimal> Quantity { get; set; }
        public Nullable<decimal> Price { get; set; }
        public Nullable<decimal> MarketValue { get; set; }
        public string OrderID { get; set; }
        public string Owner { get; set; }
        public Nullable<decimal> PL { get; set; }
        public Nullable<decimal> Fee { get; set; }
        public Nullable<decimal> PLpct { get; set; }
    }
}
