//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace dt1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PriceData
    {
        public int Id { get; set; }
        public string Coin { get; set; }
        public Nullable<System.DateTime> Timestamp { get; set; }
        public Nullable<decimal> Price { get; set; }
        public Nullable<decimal> Rank { get; set; }
        public Nullable<decimal> Rankdelta { get; set; }
        public Nullable<decimal> Marketcap { get; set; }
        public string Symbol { get; set; }
        public Nullable<decimal> MA100 { get; set; }
        public Nullable<decimal> MA7 { get; set; }
        public Nullable<decimal> MA9 { get; set; }
        public Nullable<decimal> MA50 { get; set; }
    }
}
